# -*- coding: utf-8 -*-

EXCEPTION_MESSAGE_TEXT = '‼️ EXCEPTION HAS BEEN THROWN'
GO_TO_INLINE_BUTTON = "🌀 Gallery 🌀"  # "🌄🌌 Gallery 🌃🎇"
GET_AS_FILE_BUTTON = "💾"  # "View as file"
GET_AS_PHOTO_BUTTON = "🖼"  # "View as photo"
GET_AS_FILE_CALLBACK_DATA = "F"
GET_AS_PHOTO_CALLBACK_DATA = "P"
GALLERY_TAG = "heading:\n"

NEWSLETTER_BUTTON = 'NEWSLETTER MANAGEMENT'
NEWSLETTER_CALLBACK_DATA = '/newsletter'
MAKE_NEWSLETTER_BUTTON = 'MAKE NEWSLETTER'
MAKE_NEWSLETTER_CALLBACK_DATA = '/make_newsletter'
RECALL_NEWSLETTER_BUTTON = 'RECALL NEWSLETTER'
RECALL_NEWSLETTER_CALLBACK_DATA = '/recall_newsletter'
CONFIRM_RECALL_BUTTON = 'I CONFIRM'
RECALL_CONFIRMED_CALLBACK_DATA = '/recall_confirmed'
FALSE_ALARM_BUTTON = '⬅️'
FALSE_ALARM_CALLBACK_DATA = '/false_alarm'
HIDE_MENU_BUTTON = '❌'
HIDE_MENU_CALLBACK_DATA = '/hide_menu'
ADD_RECIPIENTS_BUTTON = 'ADD SUBSCRIBERS'
ADD_RECIPIENTS_CALLBACK_DATA = '/add_recipients'
REPLY_BUTTON = 'REPLY'
REPLY_CALLBACK_DATA = '/reply'
BACKGROUND_PHOTO_BUTTON = 'SAVE BACKGROUND'
BACKGROUND_PHOTO_CALLBACK_DATA = '/s'
