# -*- coding: utf-8 -*-

EXCEPTION_MESSAGE_TEXT = '‼️ EXCEPTION HAS BEEN THROWN'
GO_TO_GALLERY_INLINE_BUTTON = "🌀"  # "🌄🌌 Gallery 🌃🎇"
GET_AS_FILE_BUTTON = "📄"  # "View as file"
GET_AS_PHOTO_BUTTON = "🖼"  # "View as photo"
GET_AS_FILE_CALLBACK_DATA = "F"
GET_AS_PHOTO_CALLBACK_DATA = "P"
GALLERY_TAG = ""
REMOVE_FROM_GALLERY_BUTTON = "🗑"
REMOVE_FROM_GALLERY_CALLBACK_DATA = "R"
CONFIRMED_REMOVE_FROM_GALLERY_CALLBACK_DATA = "C"

MAKE_NEWSLETTER_BUTTON = 'MAKE NEWSLETTER'
MAKE_NEWSLETTER_CALLBACK_DATA = '/make_newsletter'
RECALL_NEWSLETTER_BUTTON = 'RECALL NEWSLETTER'
RECALL_NEWSLETTER_CALLBACK_DATA = '/recall_newsletter'
CONFIRM_RECALL_BUTTON = 'I CONFIRM'
RECALL_CONFIRMED_CALLBACK_DATA = '/recall_confirmed'
HIDE_MENU_BUTTON = '❌'
REMOVE_CURRENT_MESSAGE_CALLBACK_DATA = '/hide_menu'
YES_REMOVE_BUTTON_TEXT = '🔥 Yes, remove 🔥'
CANCEL_REMOVING_BUTTON_TEXT = '❌ Cancel ❌'
